apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding
metadata:
  name: readOnlyBinding
roleRef:
  kind: ClusterRole
  name: readOnly
  apiGroup: rbac.authorization.k8s.io 
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: "7382d785-aba3-4392-b979-31cda3e1b16e"
