apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: key-vault-secret-env
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "csi-key-vault-handson-ay"
    objects:  |
      array:
        - |
          objectName: k8s-secret-demo
          objectType: secret
    tenantId: "449fbe1d-9c99-4509-9014-4fd5cf25b014"
  secretObjects:
  - secretName: key-vault-secret
    type: Opaque
    data:
    - objectName: k8s-secret-demo
      key: secret-content